const REMOTE_DATA="https://raw.githubusercontent.com/DnSiii/CryptoAI-Lab/paper-results/dashboard/dashboard_data.json";
const ENGINE_ORDER=["v13","v14","v15","v16","v99"];
const COLORS={v13:"#93a4b8",v14:"#5f8cff",v15:"#a477ff",v16:"#35d6e8",v99:"#b7ff4a"};
const LABELS={v13:"V13",v14:"V14",v15:"V15",v16:"V16",v99:"V99"};
const DASHBOARD_TIMEZONE="America/Sao_Paulo";
const state={data:null,view:"paper",selectedPaperEngine:"v99",selectedBacktest:new Set(ENGINE_ORDER),btDays:365};
const brl=(v,d=2)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL",minimumFractionDigits:d,maximumFractionDigits:d});
const pct=(v,d=2)=>`${Number(v||0)>=0?"+":""}${Number(v||0).toFixed(d).replace(".",",")}%`;
const date=v=>v?new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:DASHBOARD_TIMEZONE}).format(new Date(v)):"—";
const shortDate=v=>v?new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",timeZone:DASHBOARD_TIMEZONE}).format(new Date(v)):"—";
const dateTime=v=>v?new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit",timeZone:DASHBOARD_TIMEZONE}).format(new Date(v)):"—";
const cls=v=>Number(v||0)>=0?"positive":"negative";
const tzPartsFormatter=new Intl.DateTimeFormat("en-US",{timeZone:DASHBOARD_TIMEZONE,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"});
function tzParts(value){const out={};tzPartsFormatter.formatToParts(new Date(value)).forEach(p=>{if(p.type!=="literal")out[p.type]=Number(p.value)});return out}
function zonedMs(year,month,day,hour=0,minute=0,second=0){const target=Date.UTC(year,month-1,day,hour,minute,second);let guess=target;for(let i=0;i<4;i++){const p=tzParts(guess),observed=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second),diff=target-observed;guess+=diff;if(Math.abs(diff)<1000)break}return guess}
function localDayStartMs(value){const p=tzParts(value);return zonedMs(p.year,p.month,p.day,0,0,0)}
function localInputDate(value){const p=tzParts(value);return `${String(p.year).padStart(4,"0")}-${String(p.month).padStart(2,"0")}-${String(p.day).padStart(2,"0")}`}
function inputDateMs(value,endOfDay=false){if(!value)return null;const [year,month,day]=value.split("-").map(Number);return zonedMs(year,month,day,endOfDay?23:0,endOfDay?59:0,endOfDay?59:0)}
async function fetchJson(url){const r=await fetch(`${url}${url.includes("?")?"&":"?"}t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
async function loadData(){try{return await fetchJson(REMOTE_DATA)}catch(e){console.warn("remote snapshot failed",e);return fetchJson("dashboard_data.json")}}
function setView(id){state.view=id;document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===id));document.querySelector("#page-title").textContent=id==="paper"?"Visão Geral · Paper":"Visão Geral · Backtest";document.querySelector("#page-subtitle").textContent=id==="paper"?"O que os engines estão fazendo depois do boundary independente.":"Como os engines se comportaram no mesmo recorte histórico.";requestAnimationFrame(()=>id==="paper"?renderPaper():renderBacktest())}
function bindNavigation(){document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)))}
function paperEngines(){return ENGINE_ORDER.map(k=>state.data?.paper?.engines?.[k]).filter(Boolean)}
function btEngine(k){return state.data?.backtest?.engines?.[k]}
function paperCard(e){const badge=e.track==="v99"?"FROZEN":(e.role||"ENGINE");return `<article class="engine-card ${e.track} ${state.selectedPaperEngine===e.track?"selected":""}" data-paper-engine="${e.track}"><div class="engine-head"><div><small>${e.label} · ${e.role||"Engine"}</small><strong>${e.name}</strong></div><span class="tag">${badge}</span></div><div class="engine-roi ${cls(e.roiPct)}">${pct(e.roiPct)}</div><div class="engine-capital">${brl(e.currentCapitalBrl)} <span>de ${brl(e.baseCapitalBrl)}</span></div><div class="engine-meta"><div><span>Forward</span><strong>${e.newForwardHours||0}h</strong></div><div><span>Exposição</span><strong>${Number(e.grossExposurePct||0).toFixed(1).replace(".",",")}%</strong></div></div></article>`}
function renderPaperCards(){const n=document.querySelector("#paper-engine-cards");if(!n)return;n.innerHTML=paperEngines().map(paperCard).join("");n.querySelectorAll("[data-paper-engine]").forEach(card=>card.addEventListener("click",()=>{state.selectedPaperEngine=card.dataset.paperEngine;renderPaperCards();renderPaperDetail()}))}
function renderPaperDetail(){const e=state.data?.paper?.engines?.[state.selectedPaperEngine],n=document.querySelector("#paper-detail");if(!n)return;if(!e){n.innerHTML=`<div class="empty">Sem dados paper.</div>`;return}const pos=e.positions||[];n.innerHTML=`<div class="panel-head"><div><p class="eyebrow">${e.label} · DETALHE ATUAL</p><h3>${e.name}</h3></div><small>${dateTime(e.latest)} · São Paulo</small></div><div class="detail-hero"><div><span>ROI forward</span><strong class="${cls(e.roiPct)}">${pct(e.roiPct)}</strong></div><div><span>Capital</span><strong>${brl(e.currentCapitalBrl)}</strong></div></div><div class="detail-subtitle">Posições simuladas abertas</div><div class="detail-stack">${pos.length?pos.map(p=>`<div class="position-row"><strong>${p.symbol.replace("USDT","/USDT")}</strong><span class="direction ${p.direction}">${p.direction==="buy"?"COMPRA":"VENDA"}</span><span>${pct(p.weightPct,1)}</span></div>`).join(""):`<div class="empty compact-empty">Nenhuma posição aberta agora.</div>`}</div>${e.track==="v99"?`<div class="note"><strong>Satélite V99:</strong> atual ${Number(e.satelliteWeightPct||0).toFixed(2).replace(".",",")}% · alvo ${Number(e.satelliteTargetPct||0).toFixed(2).replace(".",",")}% · consenso ${Number(e.consensusPct||0).toFixed(0)}%.</div>`:""}`}
function dailyFromPaper(engine){const curve=(engine?.curve||[]).map(p=>({time:new Date(p.time).getTime(),value:Number(p.capital)})).filter(p=>Number.isFinite(p.time)&&Number.isFinite(p.value)).sort((a,b)=>a.time-b.time);if(!curve.length)return[];const byDay=new Map;curve.forEach(p=>{const key=localDayStartMs(p.time);byDay.set(key,p.value)});return[...byDay.entries()].map(([time,capital])=>({time,capital})).sort((a,b)=>a.time-b.time)}
function paperDailyRows(){const maps={},allTimes=new Set,prev={};paperEngines().forEach(e=>{const arr=dailyFromPaper(e);maps[e.track]=new Map(arr.map(x=>[x.time,x.capital]));arr.forEach(x=>allTimes.add(x.time));prev[e.track]=Number(e.baseCapitalBrl||10000)});const times=[...allTimes].sort((a,b)=>a-b);return times.map(time=>{const values={},capitals={};ENGINE_ORDER.forEach(k=>{const c=maps[k]?.get(time);capitals[k]=c;values[k]=Number.isFinite(c)&&Number.isFinite(prev[k])?(c/prev[k]-1)*100:null;if(Number.isFinite(c))prev[k]=c});return{time,values,capitals}})}
function paperSeries(mode){return paperEngines().map(e=>{const daily=dailyFromPaper(e);if(!daily.length)return null;const base=Number(e.baseCapitalBrl||daily[0].capital||10000);return{key:e.track,label:e.label,color:COLORS[e.track],points:daily.map(p=>({time:p.time,value:mode==="money"?p.capital:(p.capital/base-1)*100}))}}).filter(Boolean)}
function renderPaperInsights(rows){const n=document.querySelector("#paper-insights"),engines=paperEngines();if(!n||!engines.length)return;const leader=[...engines].sort((a,b)=>Number(b.roiPct)-Number(a.roiPct))[0],exposure=[...engines].sort((a,b)=>Number(b.grossExposurePct)-Number(a.grossExposurePct))[0],active=engines.filter(e=>(e.positions||[]).length).length,completedDays=rows.filter(r=>ENGINE_ORDER.some(k=>Number.isFinite(r.values[k]))).length;n.innerHTML=`<div class="insight-card lime"><span>Melhor ROI paper</span><strong>${leader.label} · ${pct(leader.roiPct)}</strong><small>${brl(leader.currentCapitalBrl)}</small></div><div class="insight-card"><span>Maior exposição agora</span><strong>${exposure.label} · ${Number(exposure.grossExposurePct||0).toFixed(1).replace(".",",")}%</strong><small>gross exposure</small></div><div class="insight-card"><span>Engines posicionados</span><strong>${active} de ${engines.length}</strong><small>com posição simulada aberta</small></div><div class="insight-card"><span>Dias observados</span><strong>${completedDays}</strong><small>fechamentos em America/Sao_Paulo</small></div>`;document.querySelector("#paper-leader").textContent=leader.label;document.querySelector("#paper-leader-note").textContent=`${pct(leader.roiPct)} · ${brl(leader.currentCapitalBrl)}`}
function analytics(points){if(!points||points.length<2)return{roi:0,final:1,maxDd:0,best:0,worst:0,posPct:0,avgDay:0};const first=points[0].equity,normalized=points.map(p=>({time:p.time,v:p.equity/first}));let peak=1,maxDd=0,best=-Infinity,worst=Infinity;const returns=[];for(let i=0;i<normalized.length;i++){const v=normalized[i].v;peak=Math.max(peak,v);maxDd=Math.min(maxDd,v/peak-1);if(i){const r=v/normalized[i-1].v-1;returns.push(r);best=Math.max(best,r);worst=Math.min(worst,r)}}const positive=returns.filter(r=>r>0).length;return{roi:(normalized.at(-1).v-1)*100,final:normalized.at(-1).v,maxDd:maxDd*100,best:(Number.isFinite(best)?best:0)*100,worst:(Number.isFinite(worst)?worst:0)*100,posPct:returns.length?positive/returns.length*100:0,avgDay:returns.length?returns.reduce((a,b)=>a+b,0)/returns.length*100:0}}
function btBounds(){const selected=[...state.selectedBacktest].map(btEngine).filter(Boolean),all=selected.flatMap(e=>(e.curve||[]).map(p=>new Date(p.time).getTime())).filter(Number.isFinite);if(!all.length)return{start:null,end:null};const globalEnd=Math.max(...all),from=document.querySelector("#bt-start")?.value,to=document.querySelector("#bt-end")?.value;return{start:from?inputDateMs(from,false):globalEnd-state.btDays*86400000,end:to?inputDateMs(to,true):globalEnd}}
function btPoints(key,bounds){const e=btEngine(key);if(!e)return[];return(e.curve||[]).map(p=>({time:new Date(p.time).getTime(),equity:Number(p.equity)})).filter(p=>Number.isFinite(p.time)&&Number.isFinite(p.equity)&&p.time>=bounds.start&&p.time<=bounds.end).sort((a,b)=>a.time-b.time)}
function btSeries(bounds,mode,capital){return[...state.selectedBacktest].map(key=>{const pts=btPoints(key,bounds);if(pts.length<2)return null;const first=pts[0].equity;return{key,label:btEngine(key).label,color:COLORS[key],points:pts.map(p=>({time:p.time,value:mode==="money"?capital*p.equity/first:(p.equity/first-1)*100}))}}).filter(Boolean)}
function btDailyRows(bounds){const maps={},allTimes=new Set;[...state.selectedBacktest].forEach(key=>{const pts=btPoints(key,bounds),vals=[];for(let i=1;i<pts.length;i++)vals.push([pts[i].time,(pts[i].equity/pts[i-1].equity-1)*100]);maps[key]=new Map(vals);vals.forEach(([t])=>allTimes.add(t))});return[...allTimes].sort((a,b)=>a-b).map(time=>({time,values:Object.fromEntries(ENGINE_ORDER.map(k=>[k,maps[k]?.get(time)??null]))}))}
function ddSeries(bounds){return[...state.selectedBacktest].map(key=>{const pts=btPoints(key,bounds);if(pts.length<2)return null;let peak=pts[0].equity;return{key,label:btEngine(key).label,color:COLORS[key],points:pts.map(p=>{peak=Math.max(peak,p.equity);return{time:p.time,value:(p.equity/peak-1)*100}})}}).filter(Boolean)}
function renderLegend(selector,series){const n=document.querySelector(selector);if(n)n.innerHTML=series.map(s=>`<span class="legend-item"><i style="background:${s.color}"></i>${s.label}</span>`).join("")}
function ensureStage(stageId,pointCount,perDay=72){const stage=document.querySelector(stageId);if(!stage)return;const parent=stage.parentElement,min=Math.max(parent?.clientWidth||700,Math.min(22000,Math.max(900,pointCount*perDay)));stage.style.width=`${min}px`}
function canvasSize(canvas){if(!canvas)return null;const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return null;const dpr=Math.min(window.devicePixelRatio||1,1.5);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,width:r.width,height:r.height}}
function labelValue(value,options){return options.money?`R$${Math.round(value).toLocaleString("pt-BR")}`:`${value>=0?"+":""}${value.toFixed(Math.abs(value)<10?1:0).replace(".",",")}%`}
function drawLineChart(canvas,series,options={}){if(!series.length)return;const size=canvasSize(canvas);if(!size)return;const{ctx,width,height}=size,pad={left:68,right:28,top:54,bottom:44},all=series.flatMap(s=>s.points).filter(p=>Number.isFinite(p.time)&&Number.isFinite(p.value));if(!all.length)return;const minT=Math.min(...all.map(p=>p.time)),maxT=Math.max(...all.map(p=>p.time));let minV=Math.min(...all.map(p=>p.value)),maxV=Math.max(...all.map(p=>p.value));if(options.includeZero){minV=Math.min(minV,0);maxV=Math.max(maxV,0)}const spread=Math.max(maxV-minV,Math.max(Math.abs(maxV),1)*.05);minV-=spread*.12;maxV+=spread*.18;const x=t=>pad.left+((t-minT)/Math.max(maxT-minT,1))*(width-pad.left-pad.right),y=v=>pad.top+((maxV-v)/Math.max(maxV-minV,1e-9))*(height-pad.top-pad.bottom);ctx.clearRect(0,0,width,height);ctx.font="10px Inter,system-ui";ctx.fillStyle="#718198";ctx.textAlign="right";for(let i=0;i<=4;i++){const yy=pad.top+(height-pad.top-pad.bottom)*i/4,v=maxV-(maxV-minV)*i/4;ctx.strokeStyle="rgba(148,163,184,.10)";ctx.beginPath();ctx.moveTo(pad.left,yy);ctx.lineTo(width-pad.right,yy);ctx.stroke();ctx.fillText(labelValue(v,options),pad.left-9,yy+3)}if(options.includeZero&&minV<0&&maxV>0){const yy=y(0);ctx.strokeStyle="rgba(255,255,255,.30)";ctx.beginPath();ctx.moveTo(pad.left,yy);ctx.lineTo(width-pad.right,yy);ctx.stroke()}series.forEach((s,si)=>{if(s.points.length<2)return;ctx.strokeStyle=s.color;ctx.lineWidth=s.key==="v99"?2.6:1.9;ctx.globalAlpha=s.key==="v99"?1:.82;ctx.beginPath();s.points.forEach((p,i)=>{const xx=x(p.time),yy=y(p.value);i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.stroke();ctx.globalAlpha=1;s.points.forEach((p)=>{const xx=x(p.time),yy=y(p.value);ctx.fillStyle=s.color;ctx.beginPath();ctx.arc(xx,yy,2.4,0,Math.PI*2);ctx.fill();const offset=si%2===0?-10:14;ctx.font="9px Inter,system-ui";ctx.textAlign="center";ctx.fillStyle="#dce7f5";ctx.fillText(labelValue(p.value,options),xx,yy+offset);if(si===0){ctx.fillStyle="#718198";ctx.fillText(shortDate(p.time),xx,height-12)}})})}
function drawBars(canvas,rows,keys){if(!rows.length||!keys.length)return;const size=canvasSize(canvas);if(!size)return;const{ctx,width,height}=size,pad={left:60,right:22,top:48,bottom:48},vals=rows.flatMap(r=>keys.map(k=>r.values[k])).filter(Number.isFinite);if(!vals.length)return;let min=Math.min(0,...vals),max=Math.max(0,...vals);const spread=Math.max(max-min,1);min-=spread*.16;max+=spread*.18;const y=v=>pad.top+((max-v)/Math.max(max-min,1e-9))*(height-pad.top-pad.bottom),plotW=width-pad.left-pad.right,groupW=plotW/rows.length,barW=Math.max(2,Math.min(12,(groupW*.78)/keys.length));ctx.clearRect(0,0,width,height);ctx.font="10px Inter,system-ui";ctx.textAlign="right";ctx.fillStyle="#718198";for(let i=0;i<=4;i++){const yy=pad.top+(height-pad.top-pad.bottom)*i/4,v=max-(max-min)*i/4;ctx.strokeStyle="rgba(148,163,184,.10)";ctx.beginPath();ctx.moveTo(pad.left,yy);ctx.lineTo(width-pad.right,yy);ctx.stroke();ctx.fillText(pct(v,1),pad.left-8,yy+3)}const zy=y(0);ctx.strokeStyle="rgba(255,255,255,.34)";ctx.beginPath();ctx.moveTo(pad.left,zy);ctx.lineTo(width-pad.right,zy);ctx.stroke();rows.forEach((r,idx)=>{const center=pad.left+groupW*idx+groupW/2,total=barW*keys.length;keys.forEach((k,ki)=>{const v=r.values[k];if(!Number.isFinite(v))return;const xx=center-total/2+ki*barW,yy=y(v),top=Math.min(yy,zy),h=Math.max(1,Math.abs(zy-yy));ctx.fillStyle=COLORS[k];ctx.globalAlpha=k==="v99"?1:.8;ctx.fillRect(xx,top,Math.max(1,barW-1),h);ctx.globalAlpha=1;ctx.font="8px Inter,system-ui";ctx.fillStyle="#dce7f5";ctx.textAlign="center";ctx.save();ctx.translate(xx+barW/2,v>=0?top-4:top+h+9);ctx.rotate(-Math.PI/2);ctx.fillText(pct(v,1),0,0);ctx.restore()});ctx.font="9px Inter,system-ui";ctx.fillStyle="#718198";ctx.textAlign="center";ctx.fillText(shortDate(r.time),center,height-12)})}
function renderDailyTable(selector,rows){const n=document.querySelector(selector);if(!n)return;n.innerHTML=[...rows].reverse().map(r=>{const available=ENGINE_ORDER.filter(k=>Number.isFinite(r.values[k])),winner=available.length?[...available].sort((a,b)=>r.values[b]-r.values[a])[0]:null;return`<tr><td>${date(r.time)}</td>${ENGINE_ORDER.map(k=>`<td class="${Number.isFinite(r.values[k])?cls(r.values[k]):"muted"}">${Number.isFinite(r.values[k])?pct(r.values[k]):"—"}</td>`).join("")}<td>${winner?`<span class="winner-pill ${winner}">${LABELS[winner]} · ${pct(r.values[winner])}</span>`:"—"}</td></tr>`}).join("")||`<tr><td colspan="7" class="muted">Ainda não há dias completos suficientes.</td></tr>`}
function renderPaper(){renderPaperCards();renderPaperDetail();const rows=paperDailyRows();renderPaperInsights(rows);const money=paperSeries("money"),perc=paperSeries("pct"),maxPoints=Math.max(1,...money.map(s=>s.points.length));ensureStage("#paper-money-stage",maxPoints);ensureStage("#paper-pct-stage",maxPoints);ensureStage("#paper-daily-stage",Math.max(1,rows.length),86);renderLegend("#paper-money-legend",money);renderLegend("#paper-pct-legend",perc);renderLegend("#paper-daily-legend",money);drawLineChart(document.querySelector("#paper-money-chart"),money,{money:true});drawLineChart(document.querySelector("#paper-pct-chart"),perc,{includeZero:true});drawBars(document.querySelector("#paper-daily-chart"),rows,ENGINE_ORDER.filter(k=>state.data?.paper?.engines?.[k]));renderDailyTable("#paper-daily-table",rows)}
function renderBacktestCards(bounds,capital){const n=document.querySelector("#backtest-kpis");if(!n)return;const rows=[];[...state.selectedBacktest].forEach(k=>{const pts=btPoints(k,bounds);if(pts.length<2)return;rows.push({k,e:btEngine(k),m:analytics(pts)})});rows.sort((a,b)=>ENGINE_ORDER.indexOf(a.k)-ENGINE_ORDER.indexOf(b.k));n.innerHTML=rows.map(({k,e,m})=>`<article class="engine-card analytics ${k}"><div class="engine-head"><div><small>${e.label}</small><strong>${e.name}</strong></div><span class="tag">${m.posPct.toFixed(0)}% dias +</span></div><div class="engine-roi ${cls(m.roi)}">${pct(m.roi)}</div><div class="engine-capital">${brl(capital*m.final)}</div><div class="metric-matrix"><div><span>Max DD</span><strong class="negative">${pct(m.maxDd)}</strong></div><div><span>Melhor dia</span><strong class="positive">${pct(m.best)}</strong></div><div><span>Pior dia</span><strong class="negative">${pct(m.worst)}</strong></div><div><span>Média/dia</span><strong class="${cls(m.avgDay)}">${pct(m.avgDay)}</strong></div></div></article>`).join("");if(rows.length){const leader=[...rows].sort((a,b)=>b.m.roi-a.m.roi)[0],risk=[...rows].sort((a,b)=>Math.abs(a.m.maxDd)-Math.abs(b.m.maxDd))[0],cons=[...rows].sort((a,b)=>b.m.posPct-a.m.posPct)[0];document.querySelector("#bt-leader").textContent=leader.e.label;document.querySelector("#bt-leader-note").textContent=`${pct(leader.m.roi)} · ${brl(capital*leader.m.final)}`;document.querySelector("#backtest-insights").innerHTML=`<div class="insight-card lime"><span>Maior retorno</span><strong>${leader.e.label} · ${pct(leader.m.roi)}</strong><small>${brl(capital*leader.m.final)}</small></div><div class="insight-card"><span>Menor drawdown</span><strong>${risk.e.label} · ${pct(risk.m.maxDd)}</strong><small>queda máxima do pico</small></div><div class="insight-card"><span>Mais dias positivos</span><strong>${cons.e.label} · ${cons.m.posPct.toFixed(1).replace(".",",")}%</strong><small>consistência diária</small></div><div class="insight-card"><span>Janela · São Paulo</span><strong>${date(bounds.start)} → ${date(bounds.end)}</strong><small>${Math.round((bounds.end-bounds.start)/86400000)} dias</small></div>`}}
function renderBacktest(){if(!state.data?.backtest)return;const capital=Math.max(1,Number(document.querySelector("#bt-capital")?.value||10000)),bounds=btBounds();if(!bounds.start)return;renderBacktestCards(bounds,capital);const money=btSeries(bounds,"money",capital),perc=btSeries(bounds,"pct",capital),daily=btDailyRows(bounds),dd=ddSeries(bounds),pointCount=Math.max(1,...money.map(s=>s.points.length));ensureStage("#bt-money-stage",pointCount);ensureStage("#bt-pct-stage",pointCount);ensureStage("#bt-daily-stage",Math.max(1,daily.length),86);ensureStage("#bt-dd-stage",pointCount);renderLegend("#bt-money-legend",money);renderLegend("#bt-pct-legend",perc);renderLegend("#bt-daily-legend",money);renderLegend("#bt-dd-legend",dd);drawLineChart(document.querySelector("#bt-money-chart"),money,{money:true});drawLineChart(document.querySelector("#bt-pct-chart"),perc,{includeZero:true});drawBars(document.querySelector("#bt-daily-chart"),daily,[...state.selectedBacktest]);drawLineChart(document.querySelector("#bt-dd-chart"),dd,{includeZero:true});renderDailyTable("#bt-daily-table",daily)}
function bindBacktest(){document.querySelectorAll(".preset").forEach(b=>b.addEventListener("click",()=>{state.btDays=Number(b.dataset.days);document.querySelectorAll(".preset").forEach(x=>x.classList.toggle("active",x===b));document.querySelector("#bt-start").value="";document.querySelector("#bt-end").value="";renderBacktest()}));document.querySelectorAll(".engine-toggle").forEach(b=>b.addEventListener("click",()=>{const k=b.dataset.engine;if(state.selectedBacktest.has(k)&&state.selectedBacktest.size>1)state.selectedBacktest.delete(k);else state.selectedBacktest.add(k);b.classList.toggle("active",state.selectedBacktest.has(k));renderBacktest()}));document.querySelector("#bt-capital")?.addEventListener("input",renderBacktest);document.querySelector("#bt-start")?.addEventListener("change",renderBacktest);document.querySelector("#bt-end")?.addEventListener("change",renderBacktest)}
function initDates(){const times=ENGINE_ORDER.flatMap(k=>(btEngine(k)?.curve||[]).map(p=>new Date(p.time).getTime())).filter(Number.isFinite);if(!times.length)return;const end=Math.max(...times),start=end-state.btDays*86400000;document.querySelector("#bt-start").placeholder=localInputDate(start);document.querySelector("#bt-end").placeholder=localInputDate(end)}
async function init(){try{state.data=await loadData();document.querySelector("#loading").style.display="none";document.querySelector("#runtime-text").textContent=`Snapshot ${dateTime(state.data.generatedAt)} · São Paulo`;document.querySelector("#footer-generated").textContent=`Atualizado ${dateTime(state.data.generatedAt)} · São Paulo`;bindNavigation();bindBacktest();initDates();renderPaper();window.addEventListener("resize",()=>state.view==="paper"?renderPaper():renderBacktest())}catch(e){console.error(e);document.querySelector("#loading").innerHTML=`<span class="error-dot"></span>Falha ao carregar os dados: ${e.message}`}}
document.addEventListener("DOMContentLoaded",init);
