from __future__ import annotations
import json,sys
from pathlib import Path
import numpy as np,pandas as pd
PROJECT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(PROJECT/'src')); sys.path.insert(0,str(PROJECT/'scripts'))
from cryptoai_v13.backtest import exact_fast
from cryptoai_v13.data import load_data,point_in_time_liquid_view,validate_data
import v98_independent_phase003_dispersion_neutral as p3
CONFIG_PATH=PROJECT/'config'/'v98_independent.json'; STATE_PATH=PROJECT/'state'/'v98_independent_state.json'; REPORT_PATH=PROJECT/'reports'/'v98_independent_phase014_nonbear_dispersion.json'; POSITIONS_PATH=PROJECT/'reports'/'v98_independent_phase014_nonbear_dispersion_positions.csv'
PHASE={'id':'phase_014_nonbear_dispersion','source_alpha':'phase003_frozen','gross_target':0.75,'gross_cap':0.75,'btc_trend_hours':2160,'bear_threshold':-0.15,'rebalance_hours':48}
def build_targets(data,membership):
    """Single predeclared training-diagnosed architecture: keep frozen Phase003 residual-dispersion alpha at 0.75 gross, but suppress only the pre-existing causal BTC 90d <-15% bear state. Phase013 showed bull-only routing became too sparse out of training. This is not threshold tuning: -15% is the original Phase003 regime taxonomy boundary. All features are lagged; final holdout remains inaccessible."""
    old=(p3.PHASE['gross_target'],p3.PHASE['gross_cap'])
    try:
        p3.PHASE['gross_target']=PHASE['gross_target']; p3.PHASE['gross_cap']=PHASE['gross_cap']; base=p3.build_targets(data,membership)
    finally: p3.PHASE['gross_target'],p3.PHASE['gross_cap']=old
    btc=data.close['BTCUSDT'].shift(1); nonbear=btc.pct_change(PHASE['btc_trend_hours'],fill_method=None)>=PHASE['bear_threshold']; events=np.arange(len(base))%PHASE['rebalance_hours']==0; gate=nonbear.where(pd.Series(events,index=base.index),np.nan).ffill().fillna(False).astype(float); return base.mul(gate,axis=0)
def ev(data,t,cfg,s):
    f=cfg['funding_stress'][s]; return exact_fast(data,t,cost_per_side=cfg['costs'][f'{s}_per_side'],gross_guard_cap=PHASE['gross_cap'],funding_debit_multiplier=f['debit_multiplier'],funding_credit_multiplier=f['credit_multiplier'])
def main():
    cfg=json.loads(CONFIG_PATH.read_text()); state=json.loads(STATE_PATH.read_text()); data=load_data(PROJECT,cfg['data_config']); v=validate_data(data)
    if v['errors']: raise RuntimeError(str(v['errors'][:5]))
    liquid,membership=point_in_time_liquid_view(data,top_n=p3.PHASE['liquidity_top_n'],lookback_hours=p3.PHASE['liquidity_lookback_hours'],minimum_history_hours=p3.PHASE['minimum_history_hours']); t=build_targets(liquid,membership); r={s:ev(liquid,t,cfg,s) for s in ('base','severe','supersevere')}; a,b=cfg['research_start'],cfg['training_end']; train=p3.metrics(r['base'],a,b); folds={f['name']:p3.metrics(r['base'],f['start'],f['end']) for f in cfg['folds']}; sev=p3.metrics(r['severe'],a,b); sup=p3.metrics(r['supersevere'],a,b); conc=p3.concentration_metrics(r['base'],a,b); beta=p3.beta_neutrality_metrics(r['base'],liquid,a,b); regimes=p3.regime_metrics(r['base'],liquid,a,b,b); passed,failures=p3.training_gate(train,folds,sev,sup,conc); hypothesis='Frozen Phase003 residual-dispersion alpha is structurally impaired in bear regimes but need not be restricted to bull regimes; suppress only the pre-existing causal BTC 90d <-15% bear state to retain sideways participation and reduce regime dependence.'; report={'engine':'V98 Independent','phase':PHASE,'hypothesis':hypothesis,'selection_policy':'single training-diagnosed non-bear architecture; frozen Phase003 alpha; original -15% regime boundary; no grid; legacy Jan-Jul interval validation only; final Aug-Sep holdout untouched','training':train,'folds':folds,'stress_training':{'severe':sev,'supersevere':sup},'concentration_training':conc,'beta_neutrality_training':beta,'regimes_training':regimes,'training_gate':{'passed':passed,'failures':failures},'validation':None,'final_holdout':None}
    if passed:
        v0,v1=cfg['validation_start'],cfg['validation_end']; vb=p3.metrics(r['base'],v0,v1); vs=p3.metrics(r['severe'],v0,v1); vss=p3.metrics(r['supersevere'],v0,v1); vp,vf=p3.holdout_gate(vb,vs,vss); report['validation']={'base':vb,'severe':vs,'supersevere':vss,'gate':{'passed':vp,'failures':vf}}
    REPORT_PATH.parent.mkdir(parents=True,exist_ok=True); REPORT_PATH.write_text(json.dumps(report,indent=2,default=str)+'\n'); r['base'].positions.to_csv(POSITIONS_PATH); validation_pass=bool(passed and report['validation'] and report['validation']['gate']['passed']); state['phase']='phase_014_complete'; state['last_experiment']={'id':PHASE['id'],'hypothesis':hypothesis,'status':'frozen_pending_final_holdout' if validation_pass else ('training_passed_validation_rejected' if passed else 'training_rejected'),'parameters':'frozen Phase003 at 0.75 gross; suppress original causal bear regime BTC 90d <-15%; no grid','report':str(REPORT_PATH.relative_to(PROJECT)),'training_summary':train,'folds':folds,'stress_training':report['stress_training'],'training_gate':report['training_gate'],'validation':report['validation'],'final_holdout_opened':False}; state['champion']=PHASE['id'] if validation_pass else state.get('champion'); state['final_holdout_untouched']=True; state['next_action']='If Phase014 passes training+validation, freeze code/parameters and execute one-shot final holdout. If rejected, diagnose without tuning the -15% boundary and move to an orthogonal architecture.'; STATE_PATH.write_text(json.dumps(state,indent=2,default=str)+'\n'); print(json.dumps({'phase':PHASE['id'],'training_gate':report['training_gate'],'training':train,'folds':folds,'stress':report['stress_training'],'validation':report['validation'],'final_holdout':'UNTOUCHED'},indent=2,default=str))
if __name__=='__main__': main()
