from __future__ import annotations
import json,sys
from pathlib import Path
import numpy as np,pandas as pd
PROJECT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(PROJECT/'src')); sys.path.insert(0,str(PROJECT/'scripts'))
from cryptoai_v13.backtest import exact_fast
from cryptoai_v13.data import load_data,point_in_time_liquid_view,validate_data
import v98_independent_phase003_dispersion_neutral as p3
CONFIG_PATH=PROJECT/'config'/'v98_independent.json'; STATE_PATH=PROJECT/'state'/'v98_independent_state.json'; REPORT_PATH=PROJECT/'reports'/'v98_independent_phase015_continuous_residual.json'; POSITIONS_PATH=PROJECT/'reports'/'v98_independent_phase015_continuous_residual_positions.csv'
PHASE={'id':'phase_015_continuous_residual','liquidity_top_n':10,'liquidity_lookback_hours':720,'minimum_history_hours':2160,'beta_lookback_hours':1440,'fast_hours':336,'slow_hours':1440,'volatility_lookback_hours':720,'dispersion_reference_hours':4320,'dispersion_reference_min_hours':2160,'rebalance_hours':48,'gross_target':0.75,'gross_cap':0.75}
def build_targets(data,membership):
    """Orthogonal portfolio-construction test after Phase013/014 regime routing failed validation. Keep the economically motivated residual-momentum/dispersion family, but remove unstable top/bottom membership boundaries: every eligible non-BTC asset receives a continuous centered cross-sectional residual-momentum score, inverse-vol scaled, then the event portfolio is projected onto dollar- and BTC-beta-neutral constraints. No regime filter, no threshold grid, all inputs through t-1."""
    c=PHASE; close=data.close; lag=close.shift(1); eligible=(membership & close.notna()).copy(); eligible['BTCUSDT']=False
    hourly=lag.pct_change(fill_method=None); btc=hourly['BTCUSDT']; var=btc.rolling(c['beta_lookback_hours'],min_periods=720).var(); beta=hourly.rolling(c['beta_lookback_hours'],min_periods=720).cov(btc).div(var,axis=0); residual=hourly.sub(beta.mul(btc,axis=0))
    fast=residual.rolling(c['fast_hours'],min_periods=c['fast_hours']).sum(); slow=residual.rolling(c['slow_hours'],min_periods=c['slow_hours']).sum(); score=(0.45*fast.rank(axis=1,pct=True)+0.55*slow.rank(axis=1,pct=True)-0.5).where(eligible)
    dispersion=fast.where(eligible).std(axis=1); ref=dispersion.rolling(c['dispersion_reference_hours'],min_periods=c['dispersion_reference_min_hours']).median().shift(1); active=(dispersion>ref)&ref.notna(); vol=hourly.rolling(c['volatility_lookback_hours'],min_periods=360).std(); inv=(1/vol.replace(0,np.nan)).clip(upper=50).where(eligible)
    targets=pd.DataFrame(0.0,index=close.index,columns=close.columns); events=np.arange(len(targets))%c['rebalance_hours']==0
    for ts in targets.index[events]:
        if not bool(active.get(ts,False)): continue
        ok=eligible.loc[ts] & score.loc[ts].notna() & inv.loc[ts].notna() & beta.loc[ts].notna(); names=ok.index[ok]
        if len(names)<4: continue
        y=(score.loc[ts,names]*inv.loc[ts,names]).to_numpy(float); b=beta.loc[ts,names].to_numpy(float); x=np.column_stack([np.ones(len(names)),b]); coef,*_=np.linalg.lstsq(x,y,rcond=None); neutral=y-x@coef; gross=float(np.abs(neutral).sum())
        if not np.isfinite(gross) or gross<=1e-12: continue
        targets.loc[ts,names]=neutral*(c['gross_target']/gross)
    targets=targets.where(pd.Series(events,index=targets.index),np.nan).ffill().fillna(0.0); gross=targets.abs().sum(axis=1); scale=(c['gross_cap']/gross.replace(0,np.nan)).clip(upper=1).fillna(0); return targets.mul(scale,axis=0)
def ev(data,t,cfg,s):
    f=cfg['funding_stress'][s]; return exact_fast(data,t,cost_per_side=cfg['costs'][f'{s}_per_side'],gross_guard_cap=PHASE['gross_cap'],funding_debit_multiplier=f['debit_multiplier'],funding_credit_multiplier=f['credit_multiplier'])
def main():
    cfg=json.loads(CONFIG_PATH.read_text()); state=json.loads(STATE_PATH.read_text()); data=load_data(PROJECT,cfg['data_config']); v=validate_data(data)
    if v['errors']: raise RuntimeError(str(v['errors'][:5]))
    liquid,membership=point_in_time_liquid_view(data,top_n=PHASE['liquidity_top_n'],lookback_hours=PHASE['liquidity_lookback_hours'],minimum_history_hours=PHASE['minimum_history_hours']); t=build_targets(liquid,membership); r={s:ev(liquid,t,cfg,s) for s in ('base','severe','supersevere')}; a,b=cfg['research_start'],cfg['training_end']; train=p3.metrics(r['base'],a,b); folds={f['name']:p3.metrics(r['base'],f['start'],f['end']) for f in cfg['folds']}; sev=p3.metrics(r['severe'],a,b); sup=p3.metrics(r['supersevere'],a,b); conc=p3.concentration_metrics(r['base'],a,b); beta=p3.beta_neutrality_metrics(r['base'],liquid,a,b); regimes=p3.regime_metrics(r['base'],liquid,a,b,b); passed,failures=p3.training_gate(train,folds,sev,sup,conc); hyp='Continuous residual-momentum weights can reduce discrete basket membership instability that survived training but failed Phase013/014 interval validation, while preserving causal dispersion gating and beta neutrality.'; report={'engine':'V98 Independent','phase':PHASE,'hypothesis':hyp,'selection_policy':'single orthogonal portfolio-construction architecture; no grid; training/folds/stress first; legacy Jan-Jul interval validation only; final Aug-Sep holdout untouched','training':train,'folds':folds,'stress_training':{'severe':sev,'supersevere':sup},'concentration_training':conc,'beta_neutrality_training':beta,'regimes_training':regimes,'training_gate':{'passed':passed,'failures':failures},'validation':None,'final_holdout':None}
    if passed:
        v0,v1=cfg['validation_start'],cfg['validation_end']; vb=p3.metrics(r['base'],v0,v1); vs=p3.metrics(r['severe'],v0,v1); vss=p3.metrics(r['supersevere'],v0,v1); vp,vf=p3.holdout_gate(vb,vs,vss); report['validation']={'base':vb,'severe':vs,'supersevere':vss,'gate':{'passed':vp,'failures':vf}}
    REPORT_PATH.parent.mkdir(parents=True,exist_ok=True); REPORT_PATH.write_text(json.dumps(report,indent=2,default=str)+'\n'); r['base'].positions.to_csv(POSITIONS_PATH); validation_pass=bool(passed and report['validation'] and report['validation']['gate']['passed']); state['phase']='phase_015_complete'; state['last_experiment']={'id':PHASE['id'],'hypothesis':hyp,'status':'frozen_pending_final_holdout' if validation_pass else ('training_passed_validation_rejected' if passed else 'training_rejected'),'parameters':'continuous centered residual score; dispersion gate; 0.75 gross; 48h rebalance; no grid','report':str(REPORT_PATH.relative_to(PROJECT)),'training_summary':train,'folds':folds,'stress_training':report['stress_training'],'training_gate':report['training_gate'],'validation':report['validation'],'final_holdout_opened':False}; state['champion']=PHASE['id'] if validation_pass else state.get('champion'); state['final_holdout_untouched']=True; state['next_action']='If Phase015 passes training+validation, freeze code/parameters and execute one-shot final holdout. If rejected, diagnose training evidence and move to a genuinely different alpha family rather than tuning horizons.'; STATE_PATH.write_text(json.dumps(state,indent=2,default=str)+'\n'); print(json.dumps({'phase':PHASE['id'],'training_gate':report['training_gate'],'training':train,'folds':folds,'stress':report['stress_training'],'validation':report['validation'],'final_holdout':'UNTOUCHED'},indent=2,default=str))
if __name__=='__main__': main()
